spring:
  application:
    name: tts-agent
  web:
  ai:
    openai:

      api-key: "put"
      chat:
        options:
          stream-usage: true
          model: gpt-4o-mini
          max-tokens: 20000
          temperature: 0.1
      audio:
        speech:
          options:
            model: "gpt-4o-mini-transcribe"
  output:
    ansi:
      enabled: always


audio:
  format:
    channels: 1
    sample-size-bit: 16
    sample-rate: 44100
    signed: true
    big-endian: false
file:
  output:
    output-dir: /tmp/tts
